services:
  web:
    build: ../..
    ports:
      - "4000:4000"
  backend:
    image: "registry.gitlab.com/samuel-garratt/schemaless_rest_api"
    ports:
      - "4567:4567"
    volumes:
      - ../..:/home/app/serve
